# This workflow creates a release when a build completes successfully
# on the main branch
name: release
on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches: [main]

permissions:
  contents: write

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: artifacts
      - name: Create a release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          files: |
            artifacts/*
